/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import Koneksi.koneksi;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farha
 */
public class Guru extends javax.swing.JFrame {

    /**
     * Creates new form Guru
     */
    public Guru() {
        initComponents();    
        kosong();
    }
    
    protected void kosong(){
    nipTxt.setText("");
    namaTxt.setText("");
    telpTxt.setText("");
    buttonGroup1.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nipTxt = new javax.swing.JTextField();
        telpTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        lakiLakiRb = new javax.swing.JRadioButton();
        perempuanRb = new javax.swing.JRadioButton();
        tambahBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guruTbl = new javax.swing.JTable();
        cariBtn = new javax.swing.JButton();
        cariTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        tanggalLahirDc = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Data Guru");

        jLabel2.setText("NIP");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Nama Lengkap");

        jLabel6.setText("No. Telp");

        jLabel7.setText("Tanggal Lahir");

        namaTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTxtActionPerformed(evt);
            }
        });

        buttonGroup1.add(lakiLakiRb);
        lakiLakiRb.setText("Laki - Laki");

        buttonGroup1.add(perempuanRb);
        perempuanRb.setText("Perempuan");

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        guruTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Tanggal Lahir", "Jenis Kelamin", "No Telp"
            }
        ));
        guruTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guruTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(guruTbl);

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tambahBtn)
                        .addGap(18, 18, 18)
                        .addComponent(updateBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cariBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67)
                        .addComponent(lakiLakiRb)
                        .addGap(18, 18, 18)
                        .addComponent(perempuanRb))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(137, 137, 137)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(nipTxt)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addGap(66, 66, 66)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tanggalLahirDc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(telpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1)))
                .addGap(0, 29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nipTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiLakiRb)
                        .addComponent(perempuanRb)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(telpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(tanggalLahirDc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(updateBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private koneksi conn; 
    
    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        if (!nipTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "NIP hanya boleh berisi angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String jenis = null;
        if (lakiLakiRb.isSelected()) {
            jenis = "Laki-Laki";
        } else if (perempuanRb.isSelected()) {
            jenis = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (!telpTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "No. Telp hanya boleh berisi angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tanggalLahirDc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal lahir tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String sql = "INSERT INTO guru (nip, nama_lengkap, jenis_kelamin, no_telepon, tanggal_lahir) VALUES (?,?,?,?,?)";

        try (Connection conn = koneksi.getConnection();
             PreparedStatement stat = conn.prepareStatement(sql)) {

            stat.setString(1, nipTxt.getText());
            stat.setString(2, namaTxt.getText());
            stat.setString(3, jenis);
            stat.setString(4, telpTxt.getText());
            java.sql.Date sqlDate = new java.sql.Date(tanggalLahirDc.getDate().getTime());
            stat.setDate(5, sqlDate);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            nipTxt.requestFocus();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        String nama = cariTxt.getText(); 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIP");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal Lahir");
        model.addColumn("No Telp");

        try {
            Connection conn = koneksi.getConnection();
            String sql = "SELECT * FROM guru WHERE LOWER(nama_lengkap) LIKE ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, "%" + nama.toLowerCase() + "%");

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_guru"),
                    rs.getString("nip"),
                    rs.getString("nama_lengkap"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_telepon")
                });
            }

            guruTbl.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        String jenis = null;
        if(lakiLakiRb.isSelected()){
            jenis = "Laki-Laki";
        }
        else if(perempuanRb.isSelected()){
            jenis = "Perempuan";
       }
        String sql = "update guru set nama_lengkap = ?, jenis=?, asal_sekolah=?, nisn=?, nik=?, nomor_kk=?, ttl=?, alamat=?, n_ayah=?, k_ayah=?, n_ibu=?, k_ibu=?, n_wali=?, k_wali=? where nama='"+namaTxt.getText()+"'";
        try{Connection conn = koneksi.getConnection();
            PreparedStatement stat = conn.prepareStatement(sql);  
            stat.setString(1, nipTxt.getText());
            stat.setString(2, namaTxt.getText());
            stat.setString(3, jenis);
            stat.setString(4, telpTxt.getText());
            java.sql.Date sqlDate = new java.sql.Date(tanggalLahirDc.getDate().getTime());
            stat.setDate(5, sqlDate);            
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            namaTxt.requestFocus();
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }       
    }//GEN-LAST:event_updateBtnActionPerformed

    private void namaTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTxtActionPerformed

    private void guruTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guruTblMouseClicked
              int bar = guruTbl.getSelectedRow();
        String a = guruTbl.getValueAt(bar, 1).toString();
        String b = guruTbl.getValueAt(bar, 2).toString();
        Object c = guruTbl.getValueAt(bar, 3);
        String d = guruTbl.getValueAt(bar, 4).toString();
        String e = guruTbl.getValueAt(bar, 5).toString();
        
        nipTxt.setText(a);
        namaTxt.setText(b);
//        tanggalLahirDc.setDate((Date) c);
        if ("Laki-Laki".equals(d)) {
            lakiLakiRb.setSelected(true);
            }else{
            perempuanRb.setSelected(true);
            }
        telpTxt.setText(e);
    }//GEN-LAST:event_guruTblMouseClicked

    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Guru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JTable guruTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiLakiRb;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nipTxt;
    private javax.swing.JRadioButton perempuanRb;
    private javax.swing.JButton tambahBtn;
    private com.toedter.calendar.JDateChooser tanggalLahirDc;
    private javax.swing.JTextField telpTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
