/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import Koneksi.koneksi;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author farha
 */
public class Siswa extends javax.swing.JFrame {

    /**
     * Creates new form Guru
     */
    public Siswa() {
        initComponents();
        isiComboNamaSiswa();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nisTxt = new javax.swing.JTextField();
        namaTxt = new javax.swing.JTextField();
        lakiLakiRb = new javax.swing.JRadioButton();
        perempuanRb = new javax.swing.JRadioButton();
        tambahBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        guruTbl = new javax.swing.JTable();
        cariBtn = new javax.swing.JButton();
        cariTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTxtArea = new javax.swing.JTextArea();
        kelasDd = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Siswa");

        jLabel2.setText("NIS");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Nama Lengkap");

        jLabel6.setText("Alamat");

        jLabel7.setText("Tanggal Lahir");

        nisTxt.setText("jTextField1");

        namaTxt.setText("jTextField1");

        buttonGroup1.add(lakiLakiRb);
        lakiLakiRb.setText("Laki - Laki");

        buttonGroup1.add(perempuanRb);
        perempuanRb.setText("Perempuan");

        tambahBtn.setText("Tambah");
        tambahBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBtnActionPerformed(evt);
            }
        });

        guruTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Tanggal Lahir", "Jenis Kelamin", "No Telp"
            }
        ));
        jScrollPane1.setViewportView(guruTbl);

        cariBtn.setText("Cari");
        cariBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariBtnActionPerformed(evt);
            }
        });

        cariTxt.setText("jTextField1");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        alamatTxtArea.setColumns(20);
        alamatTxtArea.setRows(5);
        jScrollPane2.setViewportView(alamatTxtArea);

        kelasDd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasDdActionPerformed(evt);
            }
        });

        jLabel8.setText("Kelas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(67, 67, 67)
                                    .addComponent(lakiLakiRb)
                                    .addGap(18, 18, 18)
                                    .addComponent(perempuanRb))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addGap(113, 113, 113)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(kelasDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cariBtn))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(137, 137, 137)
                                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tambahBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateBtn)
                                    .addGap(23, 23, 23)))
                            .addComponent(jLabel7))))
                .addGap(118, 177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nisTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiLakiRb)
                        .addComponent(perempuanRb)))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(kelasDd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahBtn)
                    .addComponent(updateBtn))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cariTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBtn))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private koneksi conn; 
    
    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBtnActionPerformed
        if (!nisTxt.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(null, "NIS hanya boleh berisi angka!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String jenis = null;
        if (lakiLakiRb.isSelected()) {
            jenis = "Laki-Laki";
        } else if (perempuanRb.isSelected()) {
            jenis = "Perempuan";
        } else {
            JOptionPane.showMessageDialog(null, "Pilih jenis kelamin!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (alamatTxtArea.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong!", "Validasi", JOptionPane.WARNING_MESSAGE);
            alamatTxtArea.requestFocus();
            return;
        }

        if (tanggalLahirDc.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Tanggal lahir tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String sql = "INSERT INTO siswa (nis, nama_lengkap, jenis_kelamin, alamat, tanggal_lahir) VALUES (?,?,?,?,?)";

        try (Connection conn = koneksi.getConnection();
             PreparedStatement stat = conn.prepareStatement(sql)) {

            stat.setString(1, nisTxt.getText());
            stat.setString(2, namaTxt.getText());
            stat.setString(3, jenis);
            stat.setString(4, alamatTxtArea.getText());
            java.sql.Date sqlDate = new java.sql.Date(tanggalLahirDc.getDate().getTime());
            stat.setDate(5, sqlDate);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            nisTxt.requestFocus();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_tambahBtnActionPerformed

    private void cariBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariBtnActionPerformed
        String nama = cariTxt.getText(); 
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NIS");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Tanggal Lahir");
        model.addColumn("Alamat");
        model.addColumn("id_kelas");

        try {
            Connection conn = koneksi.getConnection();
            String sql = "SELECT * FROM siswa  WHERE LOWER(nama_lengkap) LIKE ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, "%" + nama.toLowerCase() + "%");

            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_siswa"),
                    rs.getString("nis"),
                    rs.getString("nama_lengkap"),
                    rs.getString("tanggal_lahir"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("alamat"),
                    rs.getString("id_kelas")
                });
            }

            guruTbl.setModel(model);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_cariBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
//        String jenis = null;
//        if(lakiLakiRb.isSelected()){
//            jenis = "Laki-Laki";
//        }
//        else if(perempuanRb.isSelected()){
//            jenis = "Perempuan";
//        }
//        String sql = "update guru set nama_lengkap = ?, jenis=?, asal_sekolah=?, nisn=?, nik=?, nomor_kk=?, ttl=?, alamat=?, n_ayah=?, k_ayah=?, n_ibu=?, k_ibu=?, n_wali=?, k_wali=? where nama='"+txtnm.getText()+"'";
//        try{Connection conn = koneksi.getConnection();
//            PreparedStatement stat = conn.prepareStatement(sql);  
//            stat.setString(1, nipTxt.getText());
//            stat.setString(2, namaTxt.getText());
//            stat.setString(3, jenis);
//            stat.setString(4, telpTxt.getText());
//            java.sql.Date sqlDate = new java.sql.Date(tanggalLahirDc.getDate().getTime());
//            stat.setDate(5, sqlDate);            
//            
//            stat.executeUpdate();
//            JOptionPane.showMessageDialog(null, "data berhasil diubah");
////            kosong();
//            namaTxt.requestFocus();
//        }
//        catch (SQLException e){
//            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
//        }       
    }//GEN-LAST:event_updateBtnActionPerformed

    private void kelasDdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasDdActionPerformed
        String selected = kelasDd.getSelectedItem().toString();
        System.out.println("Yang dipilih: " + selected);
    }//GEN-LAST:event_kelasDdActionPerformed
    
    private void isiComboNamaSiswa() {
        try {
            String url = "jdbc:mysql://localhost:3306/db_sekolah";
            String user = "root";
            String password = "";

            Connection conn = DriverManager.getConnection(url, user, password);
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("SELECT nama_kelas FROM kelas");
                    
            while (rs.next()) {
                String namaKelas = rs.getString("nama_kelas");
                kelasDd.addItem(namaKelas);
//                System.out.println("Memuat: " + namaKelas);
            }

            rs.close();
            st.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Gagal load kelas: " + e.toString());
        }   
    }
    
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Siswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Siswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTxtArea;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cariBtn;
    private javax.swing.JTextField cariTxt;
    private javax.swing.JTable guruTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> kelasDd;
    private javax.swing.JRadioButton lakiLakiRb;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField nisTxt;
    private javax.swing.JRadioButton perempuanRb;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
